apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:bootstrappers
        - system:nodes
      rolearn: arn:aws:iam::12345678:role/EKSWorkerRole
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
        - system:masters
      rolearn: arn:aws:iam::12345678:role/CodeBuildRole
      username: CodeBuildRole
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system