version: 0.2
env:
  variables:
      BC_SOURCE: "codebuild"
      PRISMA_API_URL: "https://api2.prismacloud.io"
  parameter-store:
      BC_API_KEY: "bc-api-key"
      TL_USER: "tw-user"
      TL_PASS: "tw-pass"
phases:
  pre_build:
    commands:
       - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY 
  install:
    runtime-versions:
      python: 3.9
    commands:
       - echo $CODEBUILD_SRC_DIR
       - pip3 install checkov
       - echo Installing codebuild-extras...
       - curl -fsSL https://raw.githubusercontent.com/bridgecrewio/aws-codebuild-extras/master/install >> extras.sh
       - . ./extras.sh
       - curl -k -u $TL_USER:$TL_PASS https://us-east1.cloud.twistlock.com/us-2-158256885/api/v1/util/twistcli --output twistcli
       - chmod +x ./twistcli
       - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.24.11/2023-03-17/bin/linux/amd64/kubectl
       - chmod +x ./kubectl
       - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
       - kubectl version --short --client
       - aws eks --region us-west-2 update-kubeconfig --name sandeep-chandu-cluster
       - export TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
       - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
       - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
       - pip3 uninstall -y aws-sam-cli
       - checkov -d . --use-enforcement-rules --bc-api-key $BC_API_KEY --repo-id $CODEBUILD_ACCOUNT_ID/$CODEBUILD_PROJECT --branch $CODEBUILD_GIT_BRANCH -o cli -o junitxml --output-file-path console,test_results.xml
  build:
    commands:
       - ls -lrt
       - kubectl get pods
       - docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$TAG .
       - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
       - kubectl set image deployment/python-server-github python-server-app=$ECR_REGISTRY/$ECR_REPOSITORY:$TAG
       - ./twistcli images scan --details -address https://us-east1.cloud.twistlock.com/us-2-158256885 -u $TL_USER -p $TL_PASS --output-file pcc_scan_results.json --details $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
reports:
  prisma-cloud-infrastructure-security:
    files:
       - test_results.xml
    discard-paths: yes
    file-format: JunitXml
  prisma-cloud-image-security:
    files:
       - pcc_scan_results.json
    discard-paths: yes
    file-format: SimpleCovJSON
