version: 0.2
phases:
  install:
    commands:
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/darwin/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
      - kubectl version --short --client
      - aws eks --region us-west-2 update-kubeconfig --name sandeep-chandu-cluster
      - export TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - kubectl get svc
      #1. Build Image and push to ECR
      #- cd app
      #- docker build -t $ECR_REPO_URI:$TAG .
      #- $(aws ecr get-login --no-include-email)
      #- docker push $ECR_REPO_URI:$TAG
      #2. deploy newer app
      #- kubectl apply -f k8s/  